apiVersion: v1
description: Manifests, dashboards, and alerting rules for end-to-end Kubernetes cluster monitoring.
engine: gotpl
maintainers:
  - name: Giancarlo Rubio
    email: gianrubio@gmail.com
  - name: Christophe Vila
    email: christophe.vila@gemalto.com
name: ota-cloud-prometheus
sources:
  - https://github.com/coreos/prometheus-operator
version: 0.0.68
